# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: assets/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hao Tan (谭浩)
title: PhD Candidate
email: tanbox@live.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  tanhao1998
linkedin_username: tanhao1998
orcid_username: 0000-0002-9489-6543

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fas fa-graduation-cap
  url: https://scholar.google.com/citations?user=Dad3F3AAAAAJ&hl=en
- title: Download Resume
  icon: fas fa-download
  url: haotan1998.github.io/pdf/Resume.pdf

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-VSKWWKRQT4"
# google_analytics: "G-VSKWWKRQT4"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Currently, I am a second-year Ph.D. student with the School of Computing at the University of Leeds, UK. 
  It is also a joint Ph.D. program with the Dept. of Computer Science and Engineering at Southern University of Science and Technology (SUSTech), China.
  I received the B.Eng. degree in Computer Science and Engineering from SUSTech in 2020. 
  
  My current research interests are in the field of <mark>image classification</mark>, <mark>automated machine learning</mark>, and in particular <mark>evolutionary neural architecture search</mark>.
  
content:
  - title: Recent News
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **07/21**: Our paper titled "[RelativeNAS: Relative Neural Architecture Search via Slow-Fast Learning](https://arxiv.org/pdf/2009.06193)" is accepted to [IEEE T-NNLS](https://ieeexplore.ieee.org/document/9488309)!
      - **05/21**: Our paper titled "[Efficient Evolutionary Neural Architecture Search by Modular Inheritable Crossover](https://www.sciencedirect.com/science/article/pii/S2210650221000559)" is accepted to [Elsevier SWEVO](https://www.journals.elsevier.com/swarm-and-evolutionary-computation)!
  - title: Honours and Rewards 
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 2019: [BIC-TA Best Paper Award](https://www.emigroup.tech/index.php/news/undergraduate-student-tan-hao-and-others-won-the-bic-ta-2019-best-paper-award/)
  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Leeds
        sub_title: Doctor of Philosophy
        caption: October 2021 - future
        description: | # this will include new lines to allow paragraphs
          I am a Ph.D. student at the University of Leeds, under the supervision of [Dr. Nabi Omidvar](https://www.nomidvar.com) and co-supervision at SUSTech.
          The vision of my research may contain three parts: **how to analyze the neural network**, **how to design the neural network**, and **how to deploy the neural network**.       
          Firstly, I will use **Information Theory** and **Feature Visualization** to interpret the behaviour of the neural network or find the boundary of it.
          Secondly, the knowledge we discover can be used as a prior to design the neural network.
          Thirdly, we will extend the designed neural network into a search space and use **Neural Architecture Search** to further improve its performance, or for deployment purposes when considering multiple objectives.
          What is more, my long-term goal is to design a general neural network that can process multi-modal information, such as texts and images, at the same time.
      - layout: right
        title: SUSTech
        sub_title: B.Eng. in Computer Science and Technology
        caption: September 2016 - July 2020
        description: | # this will include new lines to allow paragraphs
          During my degree at SUSTech, I learnt lots of basic skills for research.
          For example, collecting and tracing papers are very important to dive into specific research areas.
          I also learnt how to use Numpy and PyTorch to start my project and realised my idea.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: SUSTech
        sub_title: Research Assistant
        caption: July 2020 - July 2021
        link: http://cse.sustech.edu.cn/en/
        link_text: Dept. of Computer Science and Engineering
        description: | # this will include new lines to allow paragraphs
          After my graduation, I continued to do the academic research for neural architecture search as a Research Assitant at SUSTech.
          During this one year, I submitted my papers into journals and handled the responses.
          At the same time, I was the **key member** and responsible for developing neural architecture search algorithms under two research giants.
  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      ## Journals
      - **Hao Tan**, Ran Cheng, Shihua Huang, Cheng He, Changxiao Qiu, Fan Yang, Ping Luo. 
      RelativeNAS: Relative Neural Architecture Search via Slow-Fast Learning. 
      *IEEE Transactions on Neural Networks and Learning Systems (TNNLS)*, 2021. [ [paper](https://arxiv.org/abs/2009.06193) / [code](https://github.com/EMI-Group/RelativeNAS) / [bibtex](tanhao1998.github.io/bibtex/tnnls21-relative.bib)]
      - Cheng He, **Hao Tan**, Shihua Huang, Ran Cheng. 
      Efficient Evolutionary Neural Architecture Search by Modular Inheritable Crossover. 
      *Swarm and Evolutionary Computation (SWEVO)*, 2021. [ [paper](https://www.sciencedirect.com/science/article/pii/S2210650221000559) ]
      
      ## Conferences
      - **Hao Tan**, Cheng He, Dexuan Tang, Ran Cheng. 
      Efficient Evolutionary Neural Architecture Search by Modular Inheritable Crossover. 
      *International Conference on Bio-inspired Computing: Theories and Applications (BIC-TA)*, 2019. (<font color="red"> Best Paper Award </font>)
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
